### ISSUE TITLE
Crash when I add widgets to Show Feed

### ISSUE THREAD

**Issue by IsaacDLS** [NeoApplications/Neo-Launcher#114]
Crash log.

Build version: 0.8.1 
Build date: 1981-01-01 01:01:02 
Current date: 2021-08-27 11:44:57 
Device: Xiaomi M2102J20SG 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=455, result=-1, data=Intent { (has extras) }} to activity {com.saggitt.omega/com.saggitt.omega.feed.FeedWidgetsActivity}: java.lang.IllegalArgumentException: Cannot find BaseActivity in parent tree
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5162)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5203)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8056)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.IllegalArgumentException: Cannot find BaseActivity in parent tree
	at com.android.launcher3.BaseActivity.fromContext(BaseActivity.java:347)
	at com.android.launcher3.Launcher.getLauncher(Launcher.java:361)
	at com.android.launcher3.widget.LauncherAppWidgetHostView.<init>(LauncherAppWidgetHostView.java:78)
	at com.android.launcher3.LauncherAppWidgetHost.onCreateView(LauncherAppWidgetHost.java:86)
	at com.android.launcher3.LauncherAppWidgetHost.onCreateView(LauncherAppWidgetHost.java:49)
	at android.appwidget.AppWidgetHost.createView(AppWidgetHost.java:402)
	at com.saggitt.omega.feed.FeedWidgetsActivity.createWidget(FeedWidgetsActivity.kt:132)
	at com.saggitt.omega.feed.FeedWidgetsActivity.configureWidget(FeedWidgetsActivity.kt:124)
	at com.saggitt.omega.feed.FeedWidgetsActivity.onActivityResult(FeedWidgetsActivity.kt:99)
	at android.app.Activity.dispatchActivityResult(Activity.java:8517)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5155)
	... 11 more

**Comment by saulhdev** [comment]
this option is not longer available in v0.9.0
