### ISSUE TITLE
crash when adding a website to homescreen

### ISSUE THREAD

**Issue by u6aab** [NeoApplications/Neo-Launcher#152]
## Description

when i try to add a website to the homescreen from firefox, omega launcher crashes

## Expected Behavior

The website should be added to the homescreen

## Actual Behavior

The launcher crashes

## Steps to Reproduce

1. go to a website in firefox
2. press "add to homescreen" in the menu

## Device and OS

* Device: google pixel 4a 5g
* Android version: 12
* Launcher version: 0.8.1
* Rom: calyxos

## Logcat

```
Build version: 0.8.1 
Build date: 1981-01-01 01:01:02 
Current date: 2022-02-21 15:37:26 
Device: Google Pixel 4a (5G) 
OS version: Android 12 (SDK 31) 
 
Stack trace:  
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.NullPointerException: drawable must not be null
	at com.saggitt.omega.iconpack.DefaultPack.getIcon(DefaultPack.kt:157)
	at com.saggitt.omega.iconpack.IconPackManager.getIcon(IconPackManager.kt:148)
	at com.saggitt.omega.icons.CustomIconProvider.getIcon(CustomIconProvider.kt:37)
	at com.android.launcher3.dragndrop.PinShortcutRequestActivityInfo.getFullResIcon(PinShortcutRequestActivityInfo.java:86)
	at com.android.launcher3.WidgetPreviewLoader.generateShortcutPreview(WidgetPreviewLoader.java:548)
	at com.android.launcher3.WidgetPreviewLoader.generatePreview(WidgetPreviewLoader.java:363)
	at com.android.launcher3.WidgetPreviewLoader.access$000(WidgetPreviewLoader.java:64)
	at com.android.launcher3.WidgetPreviewLoader$PreviewLoadTask.doInBackground(WidgetPreviewLoader.java:666)
	at com.android.launcher3.WidgetPreviewLoader$PreviewLoadTask.doInBackground(WidgetPreviewLoader.java:595)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```

**Comment by saulhdev** [comment]
Fixed on V0.9 beta 1
