### ISSUE TITLE
omega launcher crashed

### ISSUE THREAD

**Issue by AdrianBadertscher** [NeoApplications/Neo-Launcher#159]
## Description
Changed the Wallpaper and get back to HomeScreen over the Home Button.
Leads to crash report

Build version: 0.8.1 
Build date: 1981-01-01 01:01:02 
Current date: 2022-04-06 19:46:57 
Device: Samsung SM-G965F 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.android.launcher3.hybridhotseat.HotseatPredictionController.hasPredictions()' on a null object reference
	at com.android.quickstep.util.QuickstepOnboardingPrefs$4.onStateTransitionComplete(QuickstepOnboardingPrefs.java:120)
	at com.android.quickstep.util.QuickstepOnboardingPrefs$4.onStateTransitionComplete(QuickstepOnboardingPrefs.java:107)
	at com.android.launcher3.statemanager.StateManager.onStateTransitionEnd(StateManager.java:368)
	at com.android.launcher3.statemanager.StateManager.access$200(StateManager.java:44)
	at com.android.launcher3.statemanager.StateManager$1.onAnimationSuccess(StateManager.java:341)
	at com.android.launcher3.anim.AnimationSuccessListener.onAnimationEnd(AnimationSuccessListener.java:37)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:727)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Omega Launcher 0.8.1 from F-Droid

**Comment by saulhdev** [comment]
App prediction are disabled due to changes on the google APIs
