### ISSUE TITLE
Launcher 0.9.0 Build 922 crashes when opening any app

### ISSUE THREAD

**Issue by jcrabapple** [NeoApplications/Neo-Launcher#189]
## Description

Launcher 0.9.0 Build 922 crashes when opening any app from the home screen or the app drawer.

## Expected Behavior

The launcher should allow me to launch apps from the home screen and the app drawer.

## Actual Behavior

Launcher 0.9.0 Build 922 crashes when opening any app from the home screen or the app drawer.

## Steps to Reproduce

1. Install Neo Launcher
2. Set as default home app
3. Tap on app shortcut on home screen or app drawer
4. Neo Launcher crashes

## Device and OS

* Device: Pixel 6 Pro
* Android version: Android 13 Beta 4
* Launcher version: 0.9.0
* Rom:

**Comment by ayesc9000** [comment]
Adding on; I am also experiencing crashing on the Android 13 Beta.

**Comment by machiav3lli** [comment]
Crashlogs would be much appreciated

**Comment by ayesc9000** [comment]
> Crashlogs would be much appreciated

Where can I find the crash logs?

**Comment by ayesc9000** [comment]
Update 0.9.1 (build 925) seems to have fixed this issue for me.

**Comment by bobberb** [comment]
Fixed as of build 925 for me as well Android 12 Galaxy S10

**Comment by TheGreySquare** [comment]
Same issue. Android 12.1. Neo Launcher 0.9.2 (including the debug versions).

Happens with or without setting the launcher as the default home app and with or without using QuickSwitch.

Scoop crashlog (hope that's alright):

```
FATAL EXCEPTION: main
Process: com.saggitt.omega.debug, PID: 27438
java.lang.NoSuchMethodError: No static method makeRemoteAnimation(Landroid/view/RemoteAnimationAdapter;Landroid/window/IRemoteTransition;)Landroid/app/ActivityOptions; in class Landroid/app/ActivityOptions; or its super classes (declaration of 'android.app.ActivityOptions' appears in /system/framework/framework.jar)
	at com.android.systemui.shared.system.ActivityOptionsCompat.makeRemoteAnimation(ActivityOptionsCompat.java:66)
	at com.android.launcher3.QuickstepTransitionManager.getActivityLaunchOptions(QuickstepTransitionManager.java:275)
	at com.android.launcher3.BaseQuickstepLauncher.getActivityLaunchOptions(BaseQuickstepLauncher.java:448)
	at com.android.launcher3.BaseDraggingActivity.startActivitySafely(BaseDraggingActivity.java:212)
	at com.android.launcher3.Launcher.startActivitySafely(Launcher.java:2045)
	at com.android.launcher3.uioverrides.QuickstepLauncher.startActivitySafely(QuickstepLauncher.java:170)
	at com.android.launcher3.touch.ItemClickHandler.startAppShortcutOrInfoActivity(ItemClickHandler.java:360)
	at com.android.launcher3.touch.ItemClickHandler.onClickAppShortcut(ItemClickHandler.java:279)
	at com.android.launcher3.touch.ItemClickHandler.onClick(ItemClickHandler.java:93)
	at com.android.launcher3.touch.ItemClickHandler.$r8$lambda$c3IcSovkrXGdCZtXy0f_A5Sz5VA(Unknown Source:0)
	at com.android.launcher3.touch.ItemClickHandler$$ExternalSyntheticLambda2.onClick(Unknown Source:0)
	at android.view.View.performClick(View.java:7455)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28810)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7833)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
