### ISSUE TITLE
Crash when opening `Advanced Settings` > `Backups` after updating to 0.9.1

### ISSUE THREAD

**Issue by xfzv** [NeoApplications/Neo-Launcher#214]
## Description

Maybe due to https://github.com/NeoApplications/Neo-Launcher/commit/dcc276221c411cf0a4424dfb74c30c3b0d3b3d3d and https://github.com/NeoApplications/Neo-Launcher/commit/eb90d8216a2fc59f888576c58577e2af180ad577?

## Steps to Reproduce

1. Update to 0.9.1
2. Go to `Home settings` > `Advanced Settings` >  `Backups`
3. Neo-Launcher crashes

## Device and OS

* Device: OnePlus 7 Pro
* Android version: 12.1
* Launcher version: 0.9.1 (Build 925)
* Rom: YAAP Vanilla

## Logcat

```java
08-08 11:03:17.948  7606  7606 D AndroidRuntime: Shutting down VM
08-08 11:03:17.949  7606  7606 E AndroidRuntime: FATAL EXCEPTION: main
08-08 11:03:17.949  7606  7606 E AndroidRuntime: Process: com.saggitt.omega, PID: 7606
08-08 11:03:17.949  7606  7606 E AndroidRuntime: java.lang.ExceptionInInitializerError
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at com.saggitt.omega.backup.BackupListFragment.loadLocalBackups(BackupListFragment.kt:156)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at com.saggitt.omega.backup.BackupListFragment.onRecyclerViewCreated(BackupListFragment.kt:100)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at com.saggitt.omega.backup.BackupListFragment.onViewCreated(BackupListFragment.kt:77)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1808)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:538)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7877)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Illegal pattern character 'n'
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at java.text.SimpleDateFormat.compile(SimpleDateFormat.java:931)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:717)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:688)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	at com.saggitt.omega.backup.BackupFile.<clinit>(BackupFile.kt:291)
08-08 11:03:17.949  7606  7606 E AndroidRuntime: 	... 18 more
08-08 11:03:17.950  1533 10031 W ActivityTaskManager:   Force finishing activity com.saggitt.omega/.preferences.views.PreferencesActivity
08-08 11:03:17.951  1533 13915 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
08-08 11:03:17.956  1533 10031 I ActivityTaskManager: Clearing package preferred activities from com.saggitt.omega
```

**Comment by chakubie** [comment]
Same here, van confirm this..
