### ISSUE TITLE
Launcher crashes on Split Screen

### ISSUE THREAD

**Issue by Sdarfeesh** [NeoApplications/Neo-Launcher#263]
Description: Neo Launcher crashes on Split Screen

Expected Behavior: Shows the app and home screen of launcher without crash

Actual Behavior: Launcher crashed

Step to Reproduce:
1. Open an app
2. Click Split Screen
3. Screen shows the app and the home screen of launcher
4. Launcher crashes

Device: Alldocube iPlay 20
Android Version: 10.0
Launcher Version: 0.9.2 (926)
Rom: crDroid 6.11

https://user-images.githubusercontent.com/50188628/193450732-b50ce796-1ac2-4ced-9f67-16f8c8733cac.mp4

**Comment by machiav3lli** [comment]
The video is empty?! Can you please provide the crashlog?

**Comment by Sdarfeesh** [comment]
> The video is empty?! Can you please provide the crashlog?

How to

**Comment by machiav3lli** [comment]
If you have root you can use [Scoop](https://f-droid.org/en/packages/taco.scoop/) which is too easy, if not then [Matlog](https://f-droid.org/en/packages/com.pluscubed.matloglibre/) which has some steps presented in the app.

**Comment by Sdarfeesh** [comment]
> The video is empty?! Can you please provide the crashlog?

`FATAL EXCEPTION: main
Process: com.saggitt.omega, PID: 21151
java.lang.NoSuchMethodError: No interface method getMaximumWindowMetrics()Landroid/view/WindowMetrics; in class Landroid/view/WindowManager; or its super classes (declaration of 'android.view.WindowManager' appears in /system/framework/framework.jar!classes3.dex)
	at com.android.quickstep.util.SplitScreenBounds.createDefaultWindowBounds(SplitScreenBounds.java:74)
	at com.android.quickstep.util.SplitScreenBounds.getSecondaryWindowBounds(SplitScreenBounds.java:65)
	at com.android.quickstep.BaseActivityInterface.getTaskDimension(BaseActivityInterface.java:288)
	at com.android.quickstep.BaseActivityInterface.getTaskDimension(BaseActivityInterface.java:279)
	at com.android.quickstep.BaseActivityInterface.calculateTaskSizeInternal(BaseActivityInterface.java:257)
	at com.android.quickstep.BaseActivityInterface.calculateTaskSize(BaseActivityInterface.java:246)
	at com.android.quickstep.util.LayoutUtils.getShelfTrackingDistance(LayoutUtils.java:45)
	at com.android.launcher3.uioverrides.touchcontrollers.NoButtonQuickSwitchTouchController.<init>(NoButtonQuickSwitchTouchController.java:119)
	at com.android.launcher3.uioverrides.QuickstepLauncher.createTouchControllers(QuickstepLauncher.java:302)
	at com.android.launcher3.dragndrop.DragLayer.recreateControllers(DragLayer.java:111)
	at com.android.quickstep.views.RecentsView.updateOrientationHandler(RecentsView.java:1321)
	at com.android.quickstep.views.RecentsView.updateOrientationHandler(RecentsView.java:1301)
	at com.android.quickstep.views.RecentsView.setInsets(RecentsView.java:1297)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(InsettableFrameLayout.java:29)
	at com.android.launcher3.InsettableFrameLayout.setInsets(InsettableFrameLayout.java:44)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(InsettableFrameLayout.java:29)
	at com.android.launcher3.InsettableFrameLayout.setInsets(InsettableFrameLayout.java:44)
	at com.android.launcher3.LauncherRootView.dispatchInsets(LauncherRootView.java:82)
	at com.android.launcher3.statemanager.StatefulActivity.reapplyUi(StatefulActivity.java:116)
	at com.android.launcher3.statemanager.StatefulActivity.reapplyUi(StatefulActivity.java:108)
	at com.android.launcher3.Launcher.onIdpChanged(Launcher.java:579)
	at com.android.launcher3.Launcher.onConfigurationChanged(Launcher.java:568)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onConfigurationChanged(QuickstepLauncher.java:162)
	at android.app.ActivityThread.performActivityConfigurationChanged(ActivityThread.java:5525)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:5392)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:5370)
	at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:5790)
	at android.app.ActivityThread$ActivityClientRecord.lambda$init$0$ActivityThread$ActivityClientRecord(ActivityThread.java:573)
	at android.app.-$$Lambda$ActivityThread$ActivityClientRecord$H9XTv4Dku-DdbNqrbkW7UrWXxk8.onConfigurationChanged(Unknown Source:2)
	at android.view.ViewRootImpl.performConfigurationChange(ViewRootImpl.java:4399)
	at android.view.ViewRootImpl.access$400(ViewRootImpl.java:146)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4634)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)`

**Comment by Sdarfeesh** [comment]
> The video is empty?! Can you please provide the crashlog?

FATAL EXCEPTION: main
Process: com.saggitt.omega, PID: 21151
java.lang.NoSuchMethodError: No interface method getMaximumWindowMetrics()Landroid/view/WindowMetrics; in class Landroid/view/WindowManager; or its super classes (declaration of 'android.view.WindowManager' appears in /system/framework/framework.jar!classes3.dex)
	at com.android.quickstep.util.SplitScreenBounds.createDefaultWindowBounds(SplitScreenBounds.java:74)
	at com.android.quickstep.util.SplitScreenBounds.getSecondaryWindowBounds(SplitScreenBounds.java:65)
	at com.android.quickstep.BaseActivityInterface.getTaskDimension(BaseActivityInterface.java:288)
	at com.android.quickstep.BaseActivityInterface.getTaskDimension(BaseActivityInterface.java:279)
	at com.android.quickstep.BaseActivityInterface.calculateTaskSizeInternal(BaseActivityInterface.java:257)
	at com.android.quickstep.BaseActivityInterface.calculateTaskSize(BaseActivityInterface.java:246)
	at com.android.quickstep.util.LayoutUtils.getShelfTrackingDistance(LayoutUtils.java:45)
	at com.android.launcher3.uioverrides.touchcontrollers.NoButtonQuickSwitchTouchController.<init>(NoButtonQuickSwitchTouchController.java:119)
	at com.android.launcher3.uioverrides.QuickstepLauncher.createTouchControllers(QuickstepLauncher.java:302)
	at com.android.launcher3.dragndrop.DragLayer.recreateControllers(DragLayer.java:111)
	at com.android.quickstep.views.RecentsView.updateOrientationHandler(RecentsView.java:1321)
	at com.android.quickstep.views.RecentsView.updateOrientationHandler(RecentsView.java:1301)
	at com.android.quickstep.views.RecentsView.setInsets(RecentsView.java:1297)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(InsettableFrameLayout.java:29)
	at com.android.launcher3.InsettableFrameLayout.setInsets(InsettableFrameLayout.java:44)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(InsettableFrameLayout.java:29)
	at com.android.launcher3.InsettableFrameLayout.setInsets(InsettableFrameLayout.java:44)
	at com.android.launcher3.LauncherRootView.dispatchInsets(LauncherRootView.java:82)
	at com.android.launcher3.statemanager.StatefulActivity.reapplyUi(StatefulActivity.java:116)
	at com.android.launcher3.statemanager.StatefulActivity.reapplyUi(StatefulActivity.java:108)
	at com.android.launcher3.Launcher.onIdpChanged(Launcher.java:579)
	at com.android.launcher3.Launcher.onConfigurationChanged(Launcher.java:568)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onConfigurationChanged(QuickstepLauncher.java:162)
	at android.app.ActivityThread.performActivityConfigurationChanged(ActivityThread.java:5525)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:5392)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:5370)
	at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:5790)
	at android.app.ActivityThread$ActivityClientRecord.lambda$init$0$ActivityThread$ActivityClientRecord(ActivityThread.java:573)
	at android.app.-$$Lambda$ActivityThread$ActivityClientRecord$H9XTv4Dku-DdbNqrbkW7UrWXxk8.onConfigurationChanged(Unknown Source:2)
	at android.view.ViewRootImpl.performConfigurationChange(ViewRootImpl.java:4399)
	at android.view.ViewRootImpl.access$400(ViewRootImpl.java:146)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4634)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

**Comment by johnexu** [comment]
I had the same issue
