### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by Quantenzitrone** [NeoApplications/Neo-Launcher#295]
## Description

Neo Launcher crashed in the background. idk why. Maybe you can get some information from the logs.

## Steps to Reproduce
i can't

## Device and OS

* Device: SHIFT6m
* Android version: 8.1
* Launcher version: 0.9.3
* Rom: ShiftOS-L (degoogled Android by Shiftphones)

## Scoop
i got this stack trace with Scoop
```
FATAL EXCEPTION: main
Process: com.saggitt.omega, PID: 3242
java.lang.NoSuchMethodError: No interface method getMaximumWindowMetrics()Landroid/view/WindowMetrics; in class Landroid/view/WindowManager; or its super classes (declaration of 'android.view.WindowManager' appears in /system/framework/framework.jar!classes2.dex)
	at com.android.quickstep.util.SplitScreenBounds.createDefaultWindowBounds(SplitScreenBounds.java:74)
	at com.android.quickstep.util.SplitScreenBounds.getSecondaryWindowBounds(SplitScreenBounds.java:65)
	at com.android.quickstep.BaseActivityInterface.getTaskDimension(BaseActivityInterface.java:288)
	at com.android.quickstep.BaseActivityInterface.getTaskDimension(BaseActivityInterface.java:279)
	at com.android.quickstep.BaseActivityInterface.calculateTaskSizeInternal(BaseActivityInterface.java:257)
	at com.android.quickstep.BaseActivityInterface.calculateTaskSize(BaseActivityInterface.java:246)
	at com.android.quickstep.views.RecentsView.getTaskSize(RecentsView.java:1411)
	at com.android.quickstep.views.RecentsView.updateSizeAndPadding(RecentsView.java:1343)
	at com.android.quickstep.views.RecentsView.updateOrientationHandler(RecentsView.java:1333)
	at com.android.quickstep.views.RecentsView.updateOrientationHandler(RecentsView.java:1301)
	at com.android.quickstep.views.RecentsView.setInsets(RecentsView.java:1297)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(InsettableFrameLayout.java:29)
	at com.android.launcher3.InsettableFrameLayout.setInsets(InsettableFrameLayout.java:44)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(InsettableFrameLayout.java:29)
	at com.android.launcher3.InsettableFrameLayout.setInsets(InsettableFrameLayout.java:44)
	at com.android.launcher3.LauncherRootView.dispatchInsets(LauncherRootView.java:82)
	at com.android.launcher3.statemanager.StatefulActivity.reapplyUi(StatefulActivity.java:116)
	at com.android.launcher3.statemanager.StatefulActivity.reapplyUi(StatefulActivity.java:108)
	at com.android.launcher3.Launcher.onIdpChanged(Launcher.java:579)
	at com.android.launcher3.Launcher.onConfigurationChanged(Launcher.java:568)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onConfigurationChanged(QuickstepLauncher.java:162)
	at android.app.ActivityThread.performActivityConfigurationChanged(ActivityThread.java:4983)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:4850)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:4828)
	at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:5175)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1762)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6548)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```

## Logcat

```
i'll have a look later
```

**Comment by saulhdev** [comment]
Fixed in commit ec724791
