### ISSUE TITLE
Launcher keeps crashing

### ISSUE THREAD

**Issue by Erithax** [NeoApplications/Neo-Launcher#320]
## Description
Set up the launcher yesterday and now it keeps crashing: if set as the default launcher it goes in a loop crashing and restarting every couple seconds until the device prompts to change the default launcher. Opening NeoLauncher via the desktop icon or holding desktop >home settings also crashes it. I am only able to access the launcher settings via settings > apps > neo launcher > additional app settings

I was not adjusting any settings/changing the desktop when this first happened. Problem persists after cache clear, force stop app, device restart, turning off the widget, changing wallpaper and backing up launcher settings and restoring.

## Expected Behavior
N/A
## Actual Behavior
N/A
## Steps to Reproduce
Unknown

## Device and OS
* Device: 
* Android version: 12
* Launcher version: 0.9.3
* Rom: 

## Logcat
```
FATAL EXCEPTION: launcher-loader
Process: com.saggitt.omega, PID: 23327
java.lang.ClassCastException: com.android.launcher3.model.data.LauncherAppWidgetInfo cannot be cast to com.android.launcher3.model.data.FolderInfo
	at com.android.launcher3.model.QuickstepModelDelegate.modelLoadComplete(QuickstepModelDelegate.java:156)
	at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:300)
	at android.os.Handler.handleCallback(Handler.java:978)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

## PS
I have not uninstalled it yet in case you want me to gather more info somehow. Could you tell me if I can reinstall, or give me instructions on what to do?

**Comment by notYetLost** [comment]
The app just does not ask for the required access rights to storage. So when it tries to access the location for its own settings, it crashes, unless you manually give the app the necessary rights.

**Comment by notYetLost** [comment]
also, I would like to see the app on F-Droid again, where the last version is 0.8.1 dated from 2021-10-13, labelled as Omega launcher, but with identical App ID "com.saggitt.omega".
