### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by quantenzitrone** [NeoApplications/Neo-Launcher#324]
## Scoop
```
FATAL EXCEPTION: main
Process: com.saggitt.omega, PID: 14755
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.android.launcher3.model.data.ItemInfo.isDisabled()' on a null object reference
	at com.android.launcher3.util.ShortcutUtil.isActive(ShortcutUtil.java:67)
	at com.android.launcher3.util.ShortcutUtil.supportsShortcuts(ShortcutUtil.java:30)
	at com.android.launcher3.popup.PopupContainerWithArrow.canShow(PopupContainerWithArrow.java:192)
	at com.android.launcher3.popup.PopupContainerWithArrow.showForIcon(PopupContainerWithArrow.java:207)
	at com.android.launcher3.Workspace.beginDragShared(Workspace.java:1537)
	at com.android.launcher3.Workspace.beginDragShared(Workspace.java:1471)
	at com.android.launcher3.Workspace.startDrag(Workspace.java:1454)
	at com.android.launcher3.touch.ItemLongClickListener.beginDrag(ItemLongClickListener.java:78)
	at com.android.launcher3.touch.ItemLongClickListener.onWorkspaceItemLongClick(ItemLongClickListener.java:59)
	at com.android.launcher3.touch.ItemLongClickListener.$r8$lambda$nz9MSaglTImbNX-jBQmvpOY7s8M(Unknown Source:0)
	at com.android.launcher3.touch.ItemLongClickListener$$ExternalSyntheticLambda0.onLongClick(Unknown Source:0)
	at android.view.View.performLongClickInternal(View.java:6380)
	at android.view.View.performLongClick(View.java:6338)
	at android.view.View.performLongClick(View.java:6356)
	at android.view.View$CheckForLongPress.run(View.java:24906)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6548)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```

## Steps to Reproduce
i can't, but it occured after i dragged an icon from one folder in "cover mode" to another

## Device and OS

* Device: SHIFT6m
* Android version: 8.1
* Launcher version: 0.9.3
* Rom: ShiftOS-L (degoogled)

if you need any other information, let me know

**Comment by saulhdev** [comment]
Fixed in v1.0
