### ISSUE TITLE
reproducable crash when creating widget

### ISSUE THREAD

**Issue by Quantenzitrone** [NeoApplications/Neo-Launcher#326]
## Description
When dragging a widget into a space it doesnt fit but kinda does, NeoLauncher crashes

## Steps to Reproduce

1. hide dock
2. 6*16 desktop
3. try to replicate something similar as in this video:

ToDo: edit this issue on pc and add the video

## Device and OS

* Device: SHIFT6m
* Android version: 8.1
* Launcher version: 0.9.3
* Rom: ShiftOS-L (degoogled Ardroid)

## Scoop

```
FATAL EXCEPTION: main
Process: com.saggitt.omega, PID: 25118
java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1013)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:980)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:930)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:891)
	at com.android.launcher3.icons.BitmapRenderer.createSoftwareBitmap(BitmapRenderer.java:37)
	at com.android.launcher3.icons.BitmapRenderer.createHardwareBitmap(BitmapRenderer.java:45)
	at com.android.launcher3.Workspace.createWidgetDrawable(Workspace.java:2672)
	at com.android.launcher3.Workspace.animateWidgetDrop(Workspace.java:2747)
	at com.android.launcher3.Workspace.onDropExternal(Workspace.java:2587)
	at com.android.launcher3.Workspace.onDrop(Workspace.java:1824)
	at com.android.launcher3.dragndrop.DragController.drop(DragController.java:534)
	at com.android.launcher3.dragndrop.DragController.onDriverDragEnd(DragController.java:379)
	at com.android.launcher3.dragndrop.DragDriver$InternalDragDriver.onTouchEvent(DragDriver.java:183)
	at com.android.launcher3.dragndrop.DragController.onControllerTouchEvent(DragController.java:420)
	at com.android.launcher3.views.BaseDragLayer.onTouchEvent(BaseDragLayer.java:267)
	at android.view.View.dispatchTouchEvent(View.java:11808)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3016)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2666)
	at com.android.launcher3.views.BaseDragLayer.dispatchTouchEvent(BaseDragLayer.java:302)
	at com.android.launcher3.dragndrop.DragLayer.dispatchTouchEvent(DragLayer.java:214)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:449)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3307)
	at com.android.launcher3.Launcher.dispatchTouchEvent(Launcher.java:1959)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:411)
	at android.view.View.dispatchPointerEvent(View.java:12052)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4973)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4783)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4315)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4368)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4334)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4461)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4342)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4518)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4315)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4368)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4334)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4342)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4315)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6909)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6883)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6840)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7027)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:325)
	at android.os.Looper.loop(Looper.java:142)
	at android.app.ActivityThread.main(ActivityThread.java:6548)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```

**Comment by saulhdev** [comment]
duplicate of #185
