### ISSUE TITLE
Crashing on open on Android 14 QPR2 Beta 2

### ISSUE THREAD

**Issue by stardomains3** [NeoApplications/Neo-Launcher#428]
## Description

Crashing on open on Android 14 QPR2 Beta 2. 

Launch Neo Launcher
Crash

## Expected Behavior

Open

## Actual Behavior

Crash

## Steps to Reproduce

1. Open App or set as Home
2.
3.
4.

## Device and OS

Google Pixel 8 Pro
Android 14 QPR2 Beta 2 
Release 0.9.3
Google's ROM

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by machiav3lli** [comment]
A crashlog would help, you may get it using [Scoop](https://f-droid.org/en/packages/taco.scoop/)

**Comment by stardomains3** [comment]
FATAL EXCEPTION: main
Process: com.saggitt.omega, PID: 32738
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.saggitt.omega/com.saggitt.omega.OmegaLauncher}: android.view.InflateException: Binary XML file line #53 in com.saggitt.omega:layout/launcher: Binary XML file line #23 in com.saggitt.omega:layout/hotseat: Error inflating class com.saggitt.omega.blur.CustomHotseat
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3931)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4110)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:108)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:195)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:157)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:90)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2537)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8470)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.view.InflateException: Binary XML file line #53 in com.saggitt.omega:layout/launcher: Binary XML file line #23 in com.saggitt.omega:layout/hotseat: Error inflating class com.saggitt.omega.blur.CustomHotseat
Caused by: android.view.InflateException: Binary XML file line #23 in com.saggitt.omega:layout/hotseat: Error inflating class com.saggitt.omega.blur.CustomHotseat
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:742)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:894)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1118)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1007)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:972)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1014)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:972)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:570)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:462)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:413)
	at com.android.launcher3.statemanager.StatefulActivity.inflateRootView(StatefulActivity.java:67)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:455)
	at com.android.launcher3.BaseQuickstepLauncher.onCreate(BaseQuickstepLauncher.java:125)
	at com.saggitt.omega.OmegaLauncher.onCreate(OmegaLauncher.kt:221)
	at android.app.Activity.performCreate(Activity.java:8760)
	at android.app.Activity.performCreate(Activity.java:8738)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1519)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3913)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4110)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:108)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:195)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:157)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:90)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2537)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8470)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'float com.android.launcher3.ShortcutAndWidgetContainer.getAlpha()' on a null object reference
	at com.saggitt.omega.blur.CustomHotseat.getAlpha(CustomHotseat.kt:207)
	at android.view.View.getSizePercentage(View.java:33021)
	at android.view.View.votePreferredFrameRate(View.java:33047)
	at android.view.View.invalidateInternal(View.java:20218)
	at android.view.View.invalidate(View.java:20203)
	at android.view.View.setFlags(View.java:17844)
	at android.view.ViewGroup.initViewGroup(ViewGroup.java:714)
	at android.view.ViewGroup.<init>(ViewGroup.java:707)
	at android.view.ViewGroup.<init>(ViewGroup.java:701)
	at com.android.launcher3.CellLayout.<init>(CellLayout.java:239)
	at com.android.launcher3.Hotseat.<init>(Hotseat.java:63)
	at com.saggitt.omega.blur.CustomHotseat.<init>(CustomHotseat.kt:48)
	at com.saggitt.omega.blur.CustomHotseat.<init>(CustomHotseat.kt:45)
	at com.saggitt.omega.blur.CustomHotseat.<init>(Unknown Source:11)
	... 33 more
