### ISSUE TITLE
v0.8.0 broken 

### ISSUE THREAD

**Issue by Machion** [NeoApplications/Neo-Launcher#92]
## Description

I am on a motox4 with Android 9.
I used omega launcher v0.7.1 mostly without problems. After upgrading to v0.8.0 all Desktop icons are gone and the app drawer is empty. So I can't even start from beginning or use the launcher

**Comment by Surendrajat** [comment]
You need to uninstall and reinstall or need to clear data.

**Comment by summersab** [comment]
Is there a way to fix this without deleting existing data? I managed to downgrade to v0.7.1 and export my launcher settings, but v0.8.0 breaks when importing the backup. I'd really like to avoid starting from scratch since I customized a lot of things.

Let me know if you'd like a copy of my settings export and the error log. I'm happy to provide both,

**Comment by Surendrajat** [comment]
I wish I could help with that, but I'm not aware of which change breaks it. Only thing I know from telegram group is that few preferences won't work anyway, so it's better to clear data, although I understand it's time-consuming.

**Comment by otakuhqz** [comment]
Try removing custom icons from the theme preferences

**Comment by bentolor** [comment]
Same issue here. Unfortunately disabling custom icons, then removing custom icons then force stop, clear cache did not help.

Tried to export settings. This caused a null pointer error:

Build version: 0.8.0 Build date: 1981-01-01 01:01:02 Current date: 2021-06-22 20:06:15 Device: Sony Xperia Z2 Tablet Wifi OS version: Android 10 (SDK 29) Stack trace: java.lang.NullPointerException: Attempt to get length of null array 	at com.android.launcher3.model.BaseLoaderResults.bindWorkspace(BaseLoaderResults.java:88) 	at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:201) 	at android.os.Handler.handleCallback(Handler.java:883) 	at android.os.Handler.dispatchMessage(Handler.java:100) 	at android.os.Looper.loop(Looper.java:214) 	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by bentolor** [comment]
And this is the logcat containing Omega on trying to open and search the app drawer:


06-22 20:17:58.819 I/ActivityTaskManager(1600): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000100 cmp=com.saggitt.omega/.OmegaLauncher (has extras)} from uid 0 06-22 20:17:58.890 W/ActivityManager(1600): Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.saggitt.omega:10127?v=7&cv=9 pkg=com.google.android.googlequicksearchbox } U=0: not found 06-22 20:17:59.306 V/chatty (11531): uid=10127(com.saggitt.omega) identical 2 lines 06-22 20:18:03.762 E/Layer (352): [Surface(name=AppWindowToken{4c20f5f token=Token{ecaebfe ActivityRecord{7b6ebb9 u0 com.saggitt.omega/.OmegaLauncher t491}}})/@0xe9cb7e0 - animation-leash#0] No local sync point found 06-22 20:18:03.762 E/Layer (352): [Surface(name=AppWindowToken{4c20f5f token=Token{ecaebfe ActivityRecord{7b6ebb9 u0 com.saggitt.omega/.OmegaLauncher t491}}})/@0xe9cb7e0 - animation-leash#0] No local sync point found

**Comment by summersab** [comment]
My error had to do with custom tabs in the drawer (which is the one thing that I REALLY don't want to rebuild if I don't have to). I can post the logs if it would help, but it's just a little bit of a hassle to purposely corrupt my launcher to do it. :-) Let me know, though!

**Comment by otakuhqz** [comment]
If you have the logs that would be very helpful.

**Comment by otakuhqz** [comment]
> And this is the logcat containing Omega on trying to open and search the app drawer:

Do you have the Google app installed?
I changed to duck duck go search provider as default in the recents commits, so that might fix this issue.

**Comment by summersab** [comment]
Below is my error log. I also included the backup of my launcher just in case. I'm sure there's a little private info in there, but I'm pretty restrictive regarding how I use my phone, anyway. I'm not too worried.
[omega_29-06-2021 02_35_49.zip](https://github.com/otakuhqz/Omega/files/6736011/omega_29-06-2021.02_35_49.zip)

```
Build version: 0.8.0 
Build date: 1981-01-01 01:01:02 
Current date: 2021-06-29 14:38:03 
Device: LGE Nexus 5X 
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.saggitt.omega/com.saggitt.omega.OmegaLauncher}: android.view.InflateException: Binary XML file line #85 in com.saggitt.omega:layout/launcher: Binary XML file line #27 in com.saggitt.omega:layout/all_apps: Error inflating class com.saggitt.omega.allapps.AllAppsSearchContainerView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: android.view.InflateException: Binary XML file line #85 in com.saggitt.omega:layout/launcher: Binary XML file line #27 in com.saggitt.omega:layout/all_apps: Error inflating class com.saggitt.omega.allapps.AllAppsSearchContainerView
Caused by: android.view.InflateException: Binary XML file line #27 in com.saggitt.omega:layout/all_apps: Error inflating class com.saggitt.omega.allapps.AllAppsSearchContainerView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:854)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1233)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at com.saggitt.omega.OmegaLayoutInflater.inflate(OmegaLayoutInflater.kt:94)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at com.android.launcher3.statemanager.StatefulActivity.inflateRootView(StatefulActivity.java:64)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:414)
	at com.android.launcher3.BaseQuickstepLauncher.onCreate(BaseQuickstepLauncher.java:80)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:99)
	at com.saggitt.omega.OmegaLauncher.onCreate(OmegaLauncher.kt:82)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: java.lang.NumberFormatException: For input string: "UserHandle{0}"
	at java.lang.Long.parseLong(Long.java:594)
	at java.lang.Long.parseLong(Long.java:636)
	at com.android.launcher3.Utilities.makeComponentKey(Utilities.java:979)
	at com.saggitt.omega.groups.AppGroups$Group$ComponentsCustomization.unflatten(AppGroups.kt:479)
	at com.saggitt.omega.groups.AppGroups$Group$ComponentsCustomization.unflatten(AppGroups.kt:468)
	at com.saggitt.omega.groups.AppGroups$Group$SetCustomization.loadFromJson(AppGroups.kt:450)
	at com.saggitt.omega.groups.AppGroups$Group$ComponentsCustomization.loadFromJson(AppGroups.kt:472)
	at com.saggitt.omega.groups.AppGroups$Group$ComponentsCustomization.loadFromJson(AppGroups.kt:468)
	at com.saggitt.omega.groups.AppGroups$Group$Customization.loadFromJsonInternal(AppGroups.kt:233)
	at com.saggitt.omega.groups.AppGroups$Group.loadCustomizations(AppGroups.kt:205)
	at com.saggitt.omega.groups.AppGroups.loadGroups(AppGroups.kt:103)
	at com.saggitt.omega.groups.DrawerTabs.<init>(DrawerTabs.kt:68)
	at com.saggitt.omega.groups.CustomTabs.<init>(CustomTabs.kt:20)
	at com.saggitt.omega.groups.AppGroupsManager$drawerTabs$2.invoke(AppGroupsManager.kt:27)
	at com.saggitt.omega.groups.AppGroupsManager$drawerTabs$2.invoke(AppGroupsManager.kt:27)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.saggitt.omega.groups.AppGroupsManager.getDrawerTabs(AppGroupsManager.kt:27)
	at com.saggitt.omega.groups.AppGroupsManager.getModel(AppGroupsManager.kt:50)
	at com.saggitt.omega.groups.AppGroupsManager.getEnabledModel(AppGroupsManager.kt:44)
	at com.saggitt.omega.OmegaPreferences.getCurrentTabsModel(OmegaPreferences.kt:102)
	at com.saggitt.omega.allapps.AllAppsTabs.reloadTabs(AllAppsTabs.kt:51)
	at com.saggitt.omega.allapps.AllAppsTabs.<init>(AllAppsTabs.kt:45)
	at com.android.launcher3.allapps.AllAppsContainerView.<init>(AllAppsContainerView.java:133)
	at com.android.launcher3.allapps.LauncherAllAppsContainerView.<init>(LauncherAllAppsContainerView.java:46)
	at com.saggitt.omega.allapps.AllAppsSearchContainerView.<init>(AllAppsSearchContainerView.kt:31)
	at com.saggitt.omega.allapps.AllAppsSearchContainerView.<init>(AllAppsSearchContainerView.kt:27)
	at com.saggitt.omega.allapps.AllAppsSearchContainerView.<init>(Unknown Source:6)
	... 33 more
```

**Comment by machiav3lli** [comment]
@summersab not really. 0.8.0 is a re-base of the code and has a whole another data structure as the one in 0.7.1
